### PR TITLE
src/MakeTravisYml.hs: use Ubuntu 16.04

### PR DESCRIPTION
**Pull request by vaibhavsagar**

### CODE REVIEW

**Comment by phadej** [comment]
tests will fail. You need to `--accept` them.

**Comment by vaibhavsagar** [comment]
Sorry, I don't understand. Where do I need to use `--accept`?

**Comment by vaibhavsagar** [comment]
Oh, I see.

**Comment by vaibhavsagar** [comment]
@phadej all good now.

**Comment by phadej** [comment]
Thanks!

**Comment by vaibhavsagar** [comment]
My pleasure!

**Pull request merged**
