### PR TITLE
Use latest ghc version 8.6.3 to run hlint.

### PR DESCRIPTION
**Pull request by peti**

### CODE REVIEW

**Comment by phadej** [comment]
this was made obsolete by today's refactorings

**Comment by peti** [comment]
How so? I regenerated my existing .travis files and it came out running hlint in the 8.4.4 build.

**Comment by phadej** [comment]
Have you run using latest master, I fixed a bug minutes ago.

**Comment by peti** [comment]
The hlint stage doesn't work even in the latest version (b25574b57bf1cb6fd11341c2cba90357c696b23b). I run 

    haskell-ci '--doctest' '--hlint' '-o' '.travis.yml' 'hledger-interest.cabal'

but the generated output never calls `hlint` (nor `doctest`):

https://github.com/peti/hledger-interest/blob/a2ee18cef772efbd30c9a50434563ad6883fd3d2/.travis.yml#L110-L113

**Comment by phadej** [comment]
@peti please open issues for regressions, you were **very** lucky I noticed your comment on a closed issue

**Comment by phadej** [comment]
And I cannot really make a commit with "Fixes issue-N" either

**Comment by phadej** [comment]
@peti and your issue is, not related to this PR https://github.com/haskell-CI/haskell-ci/issues/170

**Comment by peti** [comment]
> @peti please open issues for regressions, you were **very** lucky I noticed your comment on a closed issue

Well, I guess I kinda objected to your closing this issue in the first place. It would have felt much more *considerate*, if you had checked with me first why I opened that PR even though it's apparently unnecessary. Then we could have had a reasonable and pleasant conversation instead of what we have now, which feels more like you berating me for trying to contribute.

**Comment by phadej** [comment]
This is PR, which became obsolete as I made changes in `master` (unfortunately not noticing this in time)

**Pull request closed without merging**
