### PR TITLE
Add shebang to the _2 version

### PR DESCRIPTION
**Pull request by Ongy**

### CODE REVIEW

**Comment by hvr** [comment]
See #110 ... unfortunately doing so interacts badly with CPP

**Comment by Ongy** [comment]
That's interesting. Does that depend on the the version? I just ran it with shebang on my (decently up to date arch) machine.

**Comment by RyanGlScott** [comment]
@Ongy, it's a [`clang`-specific issue](https://ghc.haskell.org/trac/ghc/ticket/6132), so you're unlikely to experience problems if you're not using it.

**Comment by phadej** [comment]
Non applicable anymore as this become "real" package.

**Pull request closed without merging**
