### PR TITLE
cabal-install-parsers: Construct wildcard glob directly

### LINKED ISSUE #478: `haskell-ci regenerate` fails on Windows with `packages: .`
To reproduce, build `haskell-ci` at commit 8ddf746cc3c05063306a5f90a13523774b1c5165 and create the following files:

* `experiments.cabal`:

  ```cabal
  name: experiments
  version: 1.0.0
  build-type: Simple
  cabal-version: >= 1.10
  tested-with: GHC==8.10.3
  
  library
    build-depends: base
    default-language: Haskell2010
  ```
* `cabal.project`:

  ```
  packages: .
  ```
* `.github/workflows/haskell-ci.yml`:

  ```yaml
  # REGENDATA ["github","cabal.project"]
  ```
  
If I run `haskell-ci regenerate` in this directory on Windows, it fails with:

```
$ C:\Users\winferno\Documents\Hacking\Haskell\haskell-ci\dist-newstyle\build\x86_64-windows\ghc-8.10.4\haskell-ci-0.11.20210214\x\haskell-ci\build\haskell-ci\haskell-ci regenerate
No haskell-ci.sh, skipping bash regeneration
*ERROR* Bad package location: "."
```

On the other hand, this succeeds on Linux:

```
$ /home/rscott/Documents/Hacking/Haskell/haskell-ci/dist-newstyle/build/x86_64-linux/ghc-8.10.3/haskell-ci-0.11.20210214/x/haskell-ci/build/haskell-ci/haskell-ci regenerate
No haskell-ci.sh, skipping bash regeneration
*INFO* Generating GitHub config for testing for GHC versions: 8.10.3
No .travis.yml, skipping travis regeneration
```

### PR DESCRIPTION
**Pull request by RyanGlScott**
Rather than relying on `FilePathGlob`'s `ReadP`-based parser, which behaves erratically on Windows (see #478), we now take a cue from `cabal-install` (see https://github.com/haskell/cabal/blob/d8c191d6c574d8295696e1e9b32ca16bd3cc3f5c/cabal-install/src/Distribution/Client/ProjectConfig.hs#L896-L946) and construct a glob for `./*.cabal` directly.

Fixes #478.

### CODE REVIEW

**Comment by phadej** [comment]
hlint is not happy, otherwise LGTM

**Comment by RyanGlScott** [comment]
Good catch. I've pushed a fix.

**Comment by phadej** [comment]
Thanks, this is superb

**Comment by phadej** [comment]
This broke `packages: foo/*.cabal` explicit globs.

**Comment by phadej** [comment]
Looking at this patch again, this is just wrong, as a token is never parsed as glob anymore. I'll revert the last commit.

**Comment by RyanGlScott** [comment]
My apologies for breaking things! I had hoped that I had understood the code that I copy-pasted from `cabal-install`, but sadly, my understanding was limited.

I'll take a look at #558 to see if that works on Windows.

**Pull request merged**
