### PR TITLE
Add --no-color and --no-insert-version flags

### LINKED ISSUE #276: Add a --no-color flag
Due to an unfortunate interaction with `travis_wait`, I have to manually patch the `haskell-ci`–generated `.travis.yml` file for [`base-compat`](https://github.com/haskell-compat/base-compat/pull/62/commits/a41dfd66bfd226014494beaf5ff78085d5ca7b85) to avoid the use of `color_cabal_output`. Having the ability to toggle off the use of `color` in `haskell-ci` directly would make this process easier.

### PR DESCRIPTION
**Pull request by RyanGlScott**
Fixes #276.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
The Travis build is failing due to [`hlint` complaining](https://travis-ci.org/haskell-CI/haskell-ci/jobs/535291256#L1048) about code that I didn't change:

```
$ if [ $HCNUMVER -eq 80605 ] ; then (cd haskell-ci-* && hlint -h ${TOP}/.hlint.yaml -XDeriveFoldable -XDeriveFunctor -XDeriveGeneric -XDeriveTraversable src) ; fi
src/HaskellCI/Jobs.hs:32:60: Suggestion: Avoid lambda using `infix`
Found:
  \ v -> v `withinRange` vr
Perhaps:
  (`withinRange` vr)
```

What should I do here? Should I apply the suggested change, or should I instruct `hlint` to ignore this suggestion?

**Comment by phadej** [comment]
Ryan: do you mind implementing —insert-version / —no-insert-version config and using it for all tests (and .travis.yml) in this repo. The version change churn on tests isn’t nice.

**Comment by phadej** [comment]
I’m ok with disabling use infix hint. I don’t like it :)

**Comment by RyanGlScott** [comment]
I've implemented your suggestions in https://github.com/haskell-CI/haskell-ci/pull/278#issuecomment-494414802 and https://github.com/haskell-CI/haskell-ci/pull/278#issuecomment-494415276. I've kept everything as separate commits, so let me know if you'd prefer them to be squashed into fewer commits.

**Comment by phadej** [comment]
Thanks!

**Pull request merged**
