### PR TITLE
GHC-9.2 rc1

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by nomeata** [comment]
How do I use this? I get `E: Unable to locate package ghc-9.2.0.20210821` when trying to make `inspection-testing` use this (see https://github.com/nomeata/inspection-testing/pull/64).

**Comment by phadej** [comment]
> Am I simply too fast?

Yup, wait for when ghcup adds a support. @hasufell was online today, so I hope it won't take too long for him to notice ghc-9.2-rc1 release.

**Comment by hasufell** [comment]
> > Am I simply too fast?
> 
> Yup, wait for when ghcup adds a support. @hasufell was online today, so I hope it won't take too long for him to notice ghc-9.2-rc1 release.

Was pushed a few minutes ago.

But there are a few bindists missing, eg centos and alpine.

**Comment by phadej** [comment]
ADdition: he did already: https://gitlab.haskell.org/haskell/ghcup-hs/-/commit/b86e2a1d5ba0ff213d3192ce68fec310e77c959c, so it should work now. Let me try with `hashable`

**Comment by phadej** [comment]
`hashable` jobs  passed, so adding `tested-with: GHC ==9.2.0.20210821` should work now (after upgrading `haskell-ci`, I just pushed another commit which upgrades the default `ghcup` version used, which needed an upgrade itself).

**Comment by nomeata** [comment]
Thanks all, worked perfectly!

**Pull request merged**
