### PR TITLE
GitHub Actions: GHCJS support

### PR DESCRIPTION
**Pull request by RyanGlScott**
I've tested this out on `singletons` [here](https://github.com/goldfirere/singletons/runs/2090801268), and it appears to work as you'd expect.

### CODE REVIEW

**Review by phadej — APPROVED** [review]
This looks very simple! Thanks!

I'll try this on few repositories, and if it works there too, I'll merge and make a release.

Thanks again. This is great.

**Comment by phadej** [comment]
I get errors

```
No haskell-ci.sh, skipping bash regeneration
*ERROR* ShellCheck! if echo $CC | grep -q ghcjs; then
SC1009: The mentioned syntax error was in this if expression.
SC1073: Couldn't parse this then clause. Fix to allow more checks.
SC1072: Expected a command. Fix any mentioned problems and try again.
```

when build with non GHC-9.0

**Review by phadej — CHANGES_REQUESTED** [review]
ShellCheck doesn't seem to be happy.

**Comment by RyanGlScott** [comment]
It turns out that this fails `ShellCheck`, but for some reason, `ShellCheck` doesn't run on GHC 9.0, which is what I used to test this locally. Let me think of a way to make `ShellCheck` happy...

**Comment by phadej** [comment]
We have

```haskell
SC.csShellTypeOverride = Just SC.Sh
```

atm. We could change that to `Bash`, but the justification should be good. (also macOS on GHA - which we don't yet support, but in theory that is possible too) has `bash-3` which is ancient.

**Comment by RyanGlScott** [comment]
I can convince `ShellCheck` that this is OK by turning the `if echo $CC ...` part into a single command, like so:

```diff
diff --git a/src/HaskellCI/GitHub.hs b/src/HaskellCI/GitHub.hs
index e91fa26..6dd9e0a 100644
--- a/src/HaskellCI/GitHub.hs
+++ b/src/HaskellCI/GitHub.hs
@@ -101,14 +101,15 @@ makeGitHub _argv config@Config {..} gitconfig prj jobs@JobVersions {..} = do
     steps <- sequence $ buildList $ do
         -- This have to be first, since the packages we install depend on
         -- whether we need GHCJS or not.
-        when anyGHCJS $ githubRun' "Set GHCJS environment variables" envEnv $ do
-            sh "if echo $CC | grep -q ghcjs; then"
-            tell_env "GHCJS" "true"
-            tell_env "GHCJSARITH" "1"
-            sh "else"
-            tell_env "GHCJS" "false"
-            tell_env "GHCJSARITH" "0"
-            sh "fi"
+        when anyGHCJS $ githubRun' "Set GHCJS environment variables" envEnv $ sh $ concat
+            [ "if echo $CC | grep -q ghcjs; then"
+            , "\n" ++ tell_env' "GHCJS" "true"
+            , "\n" ++ tell_env' "GHCJSARITH" "1"
+            , "\nelse"
+            , "\n" ++ tell_env' "GHCJS" "false"
+            , "\n" ++ tell_env' "GHCJSARITH" "0"
+            , "\nfi"
+            ]
 
         githubRun' "apt" envEnv $ do
             sh "apt-get update"
```

This doesn't change the output at all, only the internal data structure that `ShellCheck` examines. I've gone ahead and pushed this change.

**Pull request merged**
