### PR TITLE
Try to sort non-cwd regenerate

### PR DESCRIPTION
**Pull request by phadej**
@RyanGlScott does this work for you?

### CODE REVIEW

**Comment by phadej** [comment]
relative paths are tricky, have to think.

**Comment by RyanGlScott** [comment]
If I understand the code written here, then this is exactly what I want.

I'm not sure I understand your comments about relative paths. What challenges do they pose here that aren't normally present in other places where `OutputFile` is used?

**Comment by phadej** [comment]
If the first .travis.yml is generated out of directory, etc sillyness.

Maybe I just merge this as is, and then refactor using `paths`

**Comment by RyanGlScott** [comment]
Ah, right. It slipped my mind that `-o` has slightly different semantics in the context of `regenerate` since the file after `-o` is both an _input_ and an output.

**Pull request merged**
